export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_ORGANIZATIONS: '/admin/organizations',
  ADMIN_IMAGES: '/admin/images',
  ADMIN_LOGS: '/admin/logs',
  MANAGER_DASHBOARD: '/manager',
  MANAGER_USERS: '/manager/users',
  MANAGER_WORKSPACES: '/manager/workspaces',
  MANAGER_POLICIES: '/manager/policies',
  USER_DASHBOARD: '/user',
  USER_WORKSPACES: '/user/workspaces',
  USER_SESSIONS: '/user/sessions',
  USER_FILES: '/user/sessions/:sessionId/files',
  USER_RECORDINGS: '/user/recordings',
  USER_NOTIFICATIONS: '/user/notifications',
  PROFILE: '/profile',
  NOT_FOUND: '/404',
};